print("+-_____________________________________________________________________________________________________-+")
print("|                                                                                                       |")
print("|                                                                                       10-03-2025      |")
print("|                                                                                       Santiago, Chile |")
print("|  Querido Bastian,                                                                                     |")
print("|                                                                                                       |")
print("|        Espero que estes cumpliendo todos tus sueños y metas , esfuerzate y ponle empeño siempre,      |")
print("|        nunca te rindas y sueña en grande, recuerda que toda accion tiene su consecuencia y            |")
print("|        piensa siempre antes de hacer las cosas para luego no arrepentirte de tus actos,               |")
print("|        espero que hayas escogido una buena carrera para estudiar y que te este llendo muy bien,       |")
print("|        te deseo todo el exito para el futuro que no es muy lejano.                                    |")
print("|                                                                                                       |")
print("|        Se despide Bastian del pasado.                                                                 |")
print("|                                                                                                       |")
print("+-_____________________________________________________________________________________________________-+")